[package]
name = "task_hook"
version = "0.1.1"
edition = "2021"
authors = ["Are Jensen <arejensen@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.11"

[dev-dependencies]
tempfile = "3.20"
